/*
 * This file is a thin include shim. The actual declarations live in
 * ../../../tado-core/include/tado_core.h, generated by cbindgen from the
 * Rust source. We use a relative include so the Swift build doesn't need
 * to know about the generated path.
 */
#include "../../../tado-core/include/tado_core.h"
